### ISSUE TITLE
fix some typos in p.clip and p.insert.r

### ISSUE THREAD

**Issue by Itaykeidar** [pulp-platform/riscv#103]
o	P.clip* instructions (see attached image named so) all have same opcode. I guess RTL coding (image of RTL) is the correct one?
o	P.insert.r typo – should probably be rs2 and not ls3

also regarding p.insert.r:
We found that most likely the design and spike are behaving as expected and the problem might be the operation description.
We assume the rd bits masking is missing and some typos there so the final formula should be something like  (!(((1<< rs2[9:5]+1) - 1) << rs2[4:0]) & rD) | (rs1[rs2[9:5]:0] << rs2[4:0]) 
where !(((1<< rs2[9:5]+1) - 1) << rs2[4:0]) is a mask.

Also similar for p.insert:
(!(((1<< ls3+1) - 1) << ls2) & rD) | (rs1[Is3:0] << Is2) 

![p clip_rtl issue](https://user-images.githubusercontent.com/53673889/62419471-c269d000-b689-11e9-963f-22d751725aee.png)
![p clip_instructions](https://user-images.githubusercontent.com/53673889/62419472-c269d000-b689-11e9-84c0-61e7fcdb486b.png)
![p insert r](https://user-images.githubusercontent.com/53673889/62419474-c3026680-b689-11e9-99b5-26e932cf9ca9.png)

**Comment by dspg-arch1** [comment]
Davide, can you please verify that the RTL values above are correct (so we do not have to wait for the spec update)?

**Comment by davideschiavone** [comment]
Hello, yes the RTL is correct :) I labeled the bug as documentation as it is a documentation bug.
We are most probably rewriting the documentation in another format, thus the documentation bugs are in line and have less priority than the RTL ones :)

**Comment by davideschiavone** [comment]
61593531b7cbb22549e3d18d704b509c450ec412
