### ISSUE TITLE
Hw Loop initialization (another case)

### ISSUE THREAD

**Issue by dspg-arch1** [pulp-platform/riscv#191]
It seems that HW loop registers were applied before ID stage of the instruction in a new case.

![another](https://user-images.githubusercontent.com/47974704/68279325-d869a100-007b-11ea-83c1-a2e2d28611ea.jpg)

Maybe some speculations:
In this test we can see  reported before issue with HW loop setup instruction with IRQ.
Probably the reason why it happen is caused by instruction executed before lp.setupi. As I know execution stage rem instruction is quite long.
So ID stage of lp.setupi instruction triggers when EX stage of previous instruction is completed.
But in the waveform we can see that new values of HW loop registers were applied too quickly.

**Comment by davideschiavone** [comment]
Hello ,

which fix are you using? (which branch)
Thanks
Davide

**Comment by yaronbe1** [comment]
this one:
1.	ad00d1f
This prevents the HWloop instruction being executed if the interrupt is taken to be aligned with the other instructions

**Comment by davideschiavone** [comment]
Please apply to that also the next commit:
https://github.com/pulp-platform/riscv/commit/eb07d277b462f227dae482dec987a34181d3f1a6

Let me know if this solves the issue

**Comment by yaronbe1** [comment]
fix seams good.
you can commit.

**Comment by davideschiavone** [comment]
Thanks @yaronbe1
