### ISSUE TITLE
issue in writing logic of utvec_n

### ISSUE THREAD

**Issue by timdudu** [pulp-platform/riscv#20]
Hi,

There's an issue in the writing logic of utvec_n in csr register. The width of utvec_n is 24. But the write data is 32-bit ---> {csr_wdata_int[31:8],8'h0}.  

///----------RTL------------------------///
  logic [23:0] utvec_n, utvec_q;

     // utvec: user trap-handler base address
      12'h005: if (csr_we_int) begin
        utvec_n    = {csr_wdata_int[31:8],8'h0};

**Comment by davideschiavone** [comment]
Hi Tim,

indeed thanks. I fixed it!

Best,
Davide
