### ISSUE TITLE
Branch prediction and flushing

### ISSUE THREAD

**Issue by FrischAd** [pulp-platform/riscv#24]
Hey,
I was searching for a branch prediction unit but there seems to be none or let's say a static prediction which assumes every branch is not taken. Am I right?
When a conditional branch is taken then there is no explicit 'flush' signal set instead signals indicating a valid/not valid instruction is set?

**Comment by davideschiavone** [comment]
Hello, sorry I have seen this message only now.

Yes the prediction is "not taken" and when the branch is taken, the controller sets pc_set_o that flushes the IF stage and the instruction in the ID is not executed.

**Comment by FrischAd** [comment]
Thanks.
