### ISSUE TITLE
Illegal instruction exception with fence and fence.i instructions

### ISSUE THREAD

**Issue by mcockrell-google** [pulp-platform/riscv#26]
It is observed that execution of fence and fence.i instructions result into illegal instruction exception. It is an unexpected behavior as PULPino RI5CY core claims full support for RV32I base integer instruction set. Implementing the use case of self/cross modifying code and relaxed memory model between hardware threads will not be possible without these instructions.
Filing an issue to track resolution that is TBD.

**Comment by bluewww** [comment]
Fence and fence.i are now forcing a flush in the instruction cache in aba807b54f3bc85fde2962d0b312e22a20015c30
