### ISSUE TITLE
Documentation issue with lp.setupi instruction

### ISSUE THREAD

**Issue by mcockrell-google** [pulp-platform/riscv#29]
There is a documentation bug with lp.setupi instruction. The document describes the instruction mnemonic as given below.
lp.setupi L, uimmS, uimmL

lpstart[L] = pc + 4
lpend[L] = pc + (uimmS << 1)
lpcount[L] = uimmL
The correct mnemonic is - lp.setupi L, uimmL, uimmS

**Comment by davideschiavone** [comment]
The document has been fixed and moved to this repository

40a48c616bf7b1f8d8d2c08282a5cbc5e5072786
