### ISSUE TITLE
Streaming operator not supported in various EDA tools.

### ISSUE THREAD

**Issue by mcockrell-google** [pulp-platform/riscv#34]
The streaming operator used in riscv_alu_div  is not supported by various EDA tools and some emulators. 
`assign ResReg_DP_rev = {<<{ResReg_DP}};
`
Suggest using for loop until steaming operator support has propagated throughout EDA tool industry.

```
   always_comb begin
    for (int i = 0; i < C_WIDTH; i++) begin
      ResReg_DP_rev[i] = ResReg_DP[C_WIDTH - 1 - i];
    end
  end
```

**Comment by davideschiavone** [comment]
@igorloi fixed this problem here: 448d8cde56291c8862df839e82cb4308aeb5427f

Thanks a lot
Davide
