### ISSUE TITLE
Responding to an instruction fetch in the same cycle leaves the core deadlocked

### ISSUE THREAD

**Issue by fabianschuiki** [pulp-platform/riscv#36]
I attached an instruction cache to the core that under certain circumstances can provide a responses to an instruction request in the same cycle (`instr_req`, `instr_gnt`, and `instr_r_valid` all in the same cycle). In this case the core ignores the response and deadlocks.

See the attached image: The core requests instruction word 0x1c000090, which is granted and responded to in the same cycle. However the core is now stuck, probably ignoring the response.
![riscy_rvalid_ignored](https://user-images.githubusercontent.com/342324/38166632-279d004a-3527-11e8-9a3f-fcffc9fb30a0.png)

**Comment by gautschimi** [comment]
This behaviour is correct. Rvalid has to come 1-x cycles after a grant

Am 31. März 2018 21:23:29 MESZ schrieb Fabian Schuiki <notifications@github.com>:
>With an artificially delayed the response the core continues execution
>as expected.
>![riscy_delayed_working](https://user-images.githubusercontent.com/342324/38166773-b49e763e-3529-11e8-8a8b-1ea1db47d763.png)
> I think this is a bug :smile: 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pulp-platform/riscv/issues/36#issuecomment-377716987

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fabianschuiki** [comment]
Okay thanks, in that case I'll keep the circuitry that delays the response.
