### ISSUE TITLE
Bug for fadd.s ???

### ISSUE THREAD

**Issue by IC-Dream** [pulp-platform/riscv#53]
Hi,

From the standard IEEE 754-2008:
![infi](https://user-images.githubusercontent.com/39543344/48839710-4fece480-edc7-11e8-8662-1e86a350bb44.PNG)
addition(x, ∞) or addition( ∞, x) for finite x, we should signal no exception, but the RTL set the overflow flag and inexact flag. it violates the standard. 

Thanks
Dream

**Comment by stmach** [comment]
See #52
