### ISSUE TITLE
Illegal compressed instruction (9042) causes a parallel case fail on the unique case decoding block

### ISSUE THREAD

**Issue by ntuszynski** [pulp-platform/riscv#63]
An incoming illegal compressed instruction (value=9042) sets the ebrk_insn_i and illegal_insn_i flags simultaneously. The flags are used in an unique case block where the illegal_instruction branch is not executed, instead the ebreak_instruction branch is taken.
![Unique_Case_Fail](https://user-images.githubusercontent.com/48677309/54540134-b65dca00-4997-11e9-8327-3919ba5665c6.JPG)

**Comment by davideschiavone** [comment]
Hello, you are right.

I am fixing this

Best
Davide

**Comment by davideschiavone** [comment]
can you try again with this commit please?

2bad1016918b7195aebf4ed71f7f94ad3e0ce9d2

thanks for catching and reporting it
Davide

**Comment by ntuszynski** [comment]
My pleasure! Will try it for sure.
Thanks for quick reply.
BR,
Nicolae

**Comment by davideschiavone** [comment]
Any news @ntuszynski ?

**Comment by ntuszynski** [comment]
This one is fixed!
