### ISSUE TITLE
Does the predefined VERSION exist in get-openocd.sh?

### ISSUE THREAD

**Issue by ztrans** [pulp-platform/riscv#67]
I want to build a build environment for vcs, so I compiled gnu-toolchain in the ci directory. But when prompted to run get-opencd.sh
Fatal: reference is not a tree: af3a034b57279d2a400d87e7508c9a92254ec165
Then I went to git to find
Https://github.com/riscv/riscv-openocd/commits/
There is no version starting with af this year, is it a spelling mistake, or something else?

**Comment by ztrans** [comment]
I've found the version of openocd, but when I run the SH file I still prompt "Reference is not a tree."

**Comment by bluewww** [comment]
Sorry it is because we only clone the repo with --depth 1, I will push a fix shortly
