### ISSUE TITLE
riscv32-unknown-elf/bin/ld: can't relax section: File format not recognized

### ISSUE THREAD

**Issue by ncf125** [pulp-platform/riscv#70]
when I use https://github.com/pulp-platform/ri5cy_gnu_toolchain to run  ./tb/core/Makefile  
vcs firmware , it will report follow error.  

riscv32-unknown-elf/bin/ld: can't relax section: File format not recognized

**Comment by bluewww** [comment]
Sorry for the confusion, but this version of the compiler is meant for pulpino. The testbench in this repository work with either 
* [upstream riscv-gcc ](https://github.com/riscv/riscv-gcc), which I recommend to install by installing the whole [toolchain](https://github.com/riscv/riscv-gnu-toolchain)

or

* [pulp-riscv-gcc](https://github.com/pulp-platform/pulp-riscv-gcc), which supports our PULP specific extensions. I recommend you install the toolchain by installing our [sdk](https://github.com/pulp-platform/pulp-sdk)

I will put this information in the testbench README.
