### ISSUE TITLE
compile error when use math.h

### ISSUE THREAD

**Issue by odl-thu** [pulp-platform/riscv#95]
I need to use sin/cos function in my code, but the following error happened.
![image](https://user-images.githubusercontent.com/48423828/62274441-785ad180-b472-11e9-9f38-6492455cf948.png)

Meanwhile, I found this function can just receive constants but not variables even though I had added the -lm.

Look forward to your reply, thx!

**Comment by bluewww** [comment]
The -lm means you want to link in the math library by seaching in your (library) include paths. The compiler doesnt find it so you should make sure you provide it manually.

**Comment by odl-thu** [comment]
Thx for your answer, issue had been solved.
