### ISSUE TITLE
pv.avg - description is not fully correct, should be modulo average.

### ISSUE THREAD

**Issue by Itaykeidar** [pulp-platform/riscv#98]
pv.avg is described as an average of 2 numbers.
but due to calculation overflow thrown away after addition, result may be incorrect as "pure average"

for example:
the average of 0x8001 and 0x8005 is 0x8003.
the ri5cy gives 0x0003 result.

extension should be described as Modulo average, perhaps even change command name.

**Comment by davideschiavone** [comment]
61593531b7cbb22549e3d18d704b509c450ec412
